### ISSUE TITLE
Config API crash on 1.3.2 client

### ISSUE THREAD

**Issue by BlueStaggo** [OrnitheMC/ornithe-standard-libraries#30]
When using the Ornithe Standard Libraries on a 1.3.2 client, Minecraft crashes with this error message:
```
java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "minecraft.runDir" is null
	at net.ornithemc.osl.config.impl.client.ClientConfigInitializer.lambda$initClient$0(ClientConfigInitializer.java:14)
	at net.ornithemc.osl.core.api.events.Event.lambda$consumer$2(Event.java:35)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.ornithemc.osl.core.api.events.Event.lambda$consumer$3(Event.java:35)
	at net.minecraft.client.Minecraft.handler$zzl001$osl-lifecycle-events$osl$lifecycle$start(Minecraft.java:1933)
	at net.minecraft.client.Minecraft.init(Minecraft.java)
	at net.minecraft.client.Minecraft.run(Minecraft.java:516)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
This occurs with both 0.14.2 and 0.15.0.

**Comment by LostLuma** [comment]
See #27, this was already fixed (but the fix is not released yet).

**Comment by BlueStaggo** [comment]
Oh wow ok

**Comment by BlueStaggo** [comment]
Maybe a small hotfix release should be considered for this

**Comment by SpaceWalkerRS** [comment]
I forgot about this issue - it's been long enough thought so I'll look into a new release maybe later today
